version: '3'
services:
  eureka-server:
    build:
      context: ./server
    ports:
      - "8761:8761"

  client-service:
    build:
      context: ./client
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server

  voiture-service:
    build:
      context: ./voiture
    ports:
      - "8089:8089"
    depends_on:
      - eureka-server

  gateways:
    build:
      context: ./gateways
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
